#!/usr/bin/env bash

set -e # die on an error

source scripts/conf/remoteConf

if [ $# -ne 1 ]
then
	echo "Usage: ./scripts/deploy/clientVersion CLIENT_VERSION"
	exit -1
fi

echo "enable client version ${VERSION} on ${SERVER}..."

echo "ssh..."
echo "
	set -e # die on an error
	
	cd ${REMOTE_DIR}
	
	echo 'symlink...'
	ln -snf ${VERSION} ${STATIC_DIR}/current

	exit 0
" | ssh ${SERVER} bash

echo "done"
