#!/usr/bin/env bash

set -e # die on an error

source scripts/conf/remoteConf

echo "restart haproxy on ${SERVER}"

echo "ssh"
echo "
	# do not die on an error, as killall may not have a process to kill
	
	cd ${REMOTE_DIR}
	
	echo 'kill...'
	killall hapxory
	
	echo 'start...'
	nohup haproxy -f haproxy.conf &>${TIME}.log &
	
	exit 0
" | ssh root@${SERVER} bash

echo "done"
