#!/usr/bin/env bash

set -e # die on an error

if ! git diff-index --quiet HEAD --; then
	echo "Git tree is dirty - please commit or stash changes before pushing"
	exit 1
fi

rsync -avz -e ssh src/server/ tfocus:/home/bot/tfocus/src/server
rsync -avz --exclude=".*" -e ssh node_modules/std/ tfocus:/home/bot/tfocus/node_modules/std
rsync -avz --exclude=".*" -e ssh node_modules/fin/ tfocus:/home/bot/tfocus/node_modules/fin