#!/usr/bin/env bash

set -e # die on an error

if ! git diff-index --quiet HEAD --; then
	echo "Git tree is dirty - please commit or stash changes before pushing"
	exit 1
fi

rsync -avz -e ssh scripts/ tfocus:/home/bot/tfocus/scripts