#!/usr/bin/env node

var requireCompiler = require('require/compiler'),
	configureRequire = require('./configureRequire'),
	sys = require('sys')

configureRequire(requireCompiler)

sys.puts(requireCompiler.compile(process.argv[2], {
	// minify:false
	// squeeze:false,
	// mangle:false,
	// make_seqs: false,
	// dead_code: false,
	inline_script: true,
	ascii_only:true
	// max_line_length: 1000
}))
